version: '3.8'
services:
  python-app:
    build: 
      context: ./
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:80  # Перенаправление порта 8000 на 80 внутри контейнера

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: chara
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
