version: '3.8'

services:
  pythonapp:
    build: ./
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "4432:5432"
